# Generated by Django 4.2 on 2023-06-01 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smarthealth', '0003_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='spirometer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SpirometryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fev', models.DateField(default=None, null=True)),
                ('fvc', models.CharField(blank=True, max_length=200, null=True)),
                ('fve_fev', models.CharField(blank=True, max_length=200, null=True)),
                ('spirometer', models.CharField(blank=True, max_length=200, null=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthealth.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
