# Generated by Django 4.2 on 2023-06-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthealth', '0004_medicalrecord_spirometer_spirometryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(blank=True, choices=[('temp', 'Temperature'), ('bpm', 'BPM'), ('spirometry', 'Spirometry'), ('ecg', 'ECG')], max_length=20, null=True),
        ),
    ]
