# Generated by Django 4.2 on 2023-06-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthealth', '0005_medicalrecord_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(blank=True, choices=[('temp', 'temp'), ('bpm', 'bpm'), ('spirometry', 'spirometry'), ('ecg', 'ecg')], max_length=20, null=True),
        ),
    ]
