# Generated by Django 4.2 on 2023-06-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthealth', '0006_alter_medicalrecord_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('temp', 'temp'), ('bpm', 'bpm'), ('spirometry', 'spirometry'), ('ecg', 'ecg')], default='temp', max_length=20),
        ),
    ]
