# Generated by Django 4.2 on 2023-06-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthealth', '0007_alter_medicalrecord_record_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='Patient',
            new_name='patient',
        ),
    ]
