# Generated by Django 4.2 on 2023-06-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthealth', '0009_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='bpm',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='ecg',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='spirometry',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='temp',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
